// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSx2xizUSKa-jXTCgaNuqfwjJAcHr5Tyg',
    appId: '1:901972873197:web:b9dc26bac918ccefcfe1e4',
    messagingSenderId: '901972873197',
    projectId: 'raum-4c8cc',
    authDomain: 'raum-4c8cc.firebaseapp.com',
    databaseURL: 'https://raum-4c8cc-default-rtdb.firebaseio.com',
    storageBucket: 'raum-4c8cc.appspot.com',
    measurementId: 'G-CS6X2VQ0RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEFuNDwQslC2mP-Z_N-dbKQHC3vQf2tMM',
    appId: '1:901972873197:android:7ac2a566de70f48fcfe1e4',
    messagingSenderId: '901972873197',
    projectId: 'raum-4c8cc',
    databaseURL: 'https://raum-4c8cc-default-rtdb.firebaseio.com',
    storageBucket: 'raum-4c8cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUqdRs0gU-YIyLXD9jb2pMXzXYB5Wo7f0',
    appId: '1:901972873197:ios:12bbe10bd51c99d1cfe1e4',
    messagingSenderId: '901972873197',
    projectId: 'raum-4c8cc',
    databaseURL: 'https://raum-4c8cc-default-rtdb.firebaseio.com',
    storageBucket: 'raum-4c8cc.appspot.com',
    iosBundleId: 'com.example.arduinoProgramming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUqdRs0gU-YIyLXD9jb2pMXzXYB5Wo7f0',
    appId: '1:901972873197:ios:12bbe10bd51c99d1cfe1e4',
    messagingSenderId: '901972873197',
    projectId: 'raum-4c8cc',
    databaseURL: 'https://raum-4c8cc-default-rtdb.firebaseio.com',
    storageBucket: 'raum-4c8cc.appspot.com',
    iosBundleId: 'com.example.arduinoProgramming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSx2xizUSKa-jXTCgaNuqfwjJAcHr5Tyg',
    appId: '1:901972873197:web:f740109f0edafe6fcfe1e4',
    messagingSenderId: '901972873197',
    projectId: 'raum-4c8cc',
    authDomain: 'raum-4c8cc.firebaseapp.com',
    databaseURL: 'https://raum-4c8cc-default-rtdb.firebaseio.com',
    storageBucket: 'raum-4c8cc.appspot.com',
    measurementId: 'G-FHLDX08V02',
  );
}
